immune_cell <- readRDS('data1/immune_cell_round2.rds')
M <- subset(immune_cell, idents = c('Adgre1+M','Adgre4+M'))
M[['RNA']] <- split(M[['RNA']], f = M$orig.ident)
M <- NormalizeData(M) %>% FindVariableFeatures() %>% ScaleData() %>% RunPCA()
ElbowPlot(M, ndims = 50)
M <- RunUMAP(M, dims = 1:20, reduction = 'pca', reduction.name = 'umap.unintegrated')
DimPlot(M, reduction = 'umap.unintegrated', split.by = 'stim')
M <- IntegrateLayers(object = M, method = CCAIntegration, orig.reduction = "pca", new.reduction = "integrated.cca",
                       verbose = T, k.weight = 50)
M[['RNA']] <- JoinLayers(M[['RNA']])
M <- RunUMAP(M, dims = 1:20, reduction = 'integrated.cca', reduction.name = 'umap.cca')
DimPlot(M, reduction = 'umap.cca')
FeaturePlot(M, features = 'Itgal', reduction = 'umap.cca')
M <- FindNeighbors(M, reduction = 'integrated.cca', dims = 1:20)
a <- seq(from = 0.1, to = 1.5, by = 0.1)
M <- FindClusters(M ,resolution = a)
DimPlot(M ,reduction = 'umap.cca', group.by = 'RNA_snn_res.0.2' ,label = T)
Idents(M) <- 'RNA_snn_res.0.2'
M.markers <- FindAllMarkers(M, min.pct = 0.25, logfc.threshold = 0.25, only.pos = T)
saveRDS(M.markers, file = 'data1/M_markers.rds')
top30 <- M.markers %>% group_by(cluster) %>% top_n(n = 30, wt = avg_log2FC)
saveRDS(top30, file = 'data1/M_immune_top30.rds')
top30.list <- split(top30, f = top30$cluster)
openxlsx::write.xlsx(top30.list, file = "data1/top30_M_immune.xlsx")
